name: 'Setup Infisical Action'
author: '@fataldev'
description: 'Installs infisical in the runner and exports the INFISICAL_TOKEN.'
inputs:
  INFISICAL_TOKEN:
    description: 'The Infisical token to use for authentication.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install Infisical
      shell: bash
      run: |
        # Install Infisical CLI to inject environment variables
        curl -1sLf 'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.deb.sh' | sudo -E bash
        sudo apt-get update && sudo apt-get install -y infisical

        # Export Infisical token
        echo "INFISICAL_TOKEN=${{ inputs.INFISICAL_TOKEN }}" >> $GITHUB_ENV

        # Ensure Infisical was installed
        infisical --version || exit 1
